<h3 style="font-family: Arial;">Dear, <?php echo $user['su_fullname']; ?></h3>
<p style="font-family: Arial;">
    We've received a request to recover your <b>Worksaurus Team</b> account password.<br>
    If you did not make this request yourself, ignore this email and contact your administrator.
</p>
<p style="font-family: Arial;">
    If you would like to reset your password follow the link bellow. This link will expire in 8 hours.
</p>
<p style="font-family: Arial;">
    <a href="<?php echo $href; ?>"><?php echo $href; ?></a>
</p>

<p style="font-family: Arial; font-size: 12px;">
    These email contains sensitive information, please do not forward.<br>
    If you have any questions, feel free to contact us at <a href="mailto:support@worksaurus.com"><b>support@worksaurus.com</b></a><br>
    <br>
    Thank you.
</p>