<h3 style="font-family: Arial;">Dear, <?php echo $user['su_fullname']; ?></h3>
<p style="font-family: Arial;">
    Kami menerima permintaan perubahan password dari Anda.<br>
    Jika Anda tidak pernah melakukan permintaan tersebut, abaikan saja pesan ini.
</p>
<p style="font-family: Arial;">
    Jika Anda ingin merubah password Anda, silahkan klik link di bawah ini. Link hanya aktif selama 8 jam.
</p>
<p style="font-family: Arial;">
    <a href="<?php echo $href; ?>"><?php echo $href; ?></a>
</p>

<p style="font-family: Arial; font-size: 12px;">
    Email ini mengandung informasi yang sensitif. Jangan forward email ini ke orang lain.<br>
    Jika ada pertanyaan, silahkan kontak kami di <a href="mailto:tanagadevel@gmail.com"><b>tanagadevel@gmail.com</b></a><br>
    <br>
    Terima kasih.
</p>