<h3 style="font-family: Arial;">Dear, <?php echo $name; ?></h3>

<p style="font-family: Arial;">
    Akun Anda sudah aktif dan dapat digunakan untuk login ke dalam aplikasi.<br>
</p>

<p style="font-family: Arial;">
    <a href="<?php echo $link; ?>">LOGIN</a>
</p>

<p style="font-family: Arial; font-size: 12px;">
    Email ini mengandung informasi yang sensitif. Jangan forward email ini ke orang lain.<br>
    Jika ada pertanyaan, silahkan kontak kami di <a href="mailto:tanagadevel@gmail.com"><b>tanagadevel@gmail.com</b></a><br>
    <br>
    Terima kasih.
</p>